name = "hn-feed"
main = "index.ts"
compatibility_date = "2026-05-18"

[vars]
WORKERS_DOMAIN = "hn-feed.<your-subdomain>.workers.dev"

[[d1_databases]]
binding = "DB"
database_name = "hn-feed"
database_id = "e3e14322-b111-49a2-b734-6316fc3c6809"
migrations_dir = "../migrations"
