"$schema" = "./node_modules/wrangler/config-schema.json"
name = "hn-feed-admin"
main = "index.ts"
compatibility_date = "2026-05-18"

[[d1_databases]]
binding = "DB"
database_name = "hn-feed"
database_id = "e3e14322-b111-49a2-b734-6316fc3c6809"
migrations_dir = "../migrations"

[[queues.producers]]
binding = "QUEUE"
queue = "hn-processor"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = true
