name = "hn-feed"
main = "src/index.ts"
compatibility_date = "2026-04-20"

[vars]
WORKERS_DOMAIN = "hn-feed.<your-subdomain>.workers.dev"

[[kv_namespaces]]
binding = "KV"
id = "3aa1dbdb290f4be5918ab695274b28d1"
preview_id = "36129582926848b78c3a449caf612a32"
